### ISSUE TITLE
schema.rb contains rowid for join tables without id

### ISSUE THREAD

**Issue by Piioo** [cockroachdb/activerecord-cockroachdb-adapter#203]
Hello,

when we create a join table without id, then the schema.rb looks good.
```ruby
create_table :foo_bars, id: false do |t|
   t.uuid :foo_id
   t.uuid :bar_id
end
```

`create_table "foo_bars", id: false, force: :cascade do |t|`

But when we run another migration, then into the table definition in schema.rb is added a `rowid`.
`t.bigserial "rowid", null: false`

**Comment by keithdoggett** [comment]
I tried this and was able to replicate it. I saw that the SQL generated was correct though and does not include anything about rowid. After looking into it I came across this https://www.cockroachlabs.com/docs/v20.2/create-table.html#create-a-table. Which states:

> In CockroachDB, every table requires a primary key. If one is not explicitly defined, a column called rowid of the type INT is added automatically as the primary key, with the unique_rowid() function used to ensure that new rows always default to unique rowid values.

Maybe @rafiss knows if it's possible to bypass this, but it seems like this is the expected behavior and passing `id: false` into the `create_table` statement won't do anything.

**Comment by Piioo** [comment]
But the problem is, that the rails default tasks do not work correct with this.

Here how the database looks like after migration:
<img width="1024" alt="Bildschirmfoto 2021-05-18 um 15 14 07" src="https://user-images.githubusercontent.com/4640423/118657466-cda0d800-b7eb-11eb-9764-3f89ec29650a.png">

But when I remove the whole datebase and load the schema from the schema.rb (without removing the rowid)
`bundle exec rails db:drop db:create db:schema:laod`

It looks like this:
<img width="1024" alt="Bildschirmfoto 2021-05-18 um 15 16 20" src="https://user-images.githubusercontent.com/4640423/118657740-0640b180-b7ec-11eb-8f8c-9c8033b796fe.png">

**Comment by keithdoggett** [comment]
Ok, so the problem is that it will create a new `rowid_#{n}` row every time the schema is reloaded into the database? I think the best option is to just ignore the `id` parameter then if it doesn't do anything anyways.

**Comment by Piioo** [comment]
Version 6.1.1 is different. It creates this in schema.rb:

`create_table "foo_users", primary_key: "rowid_1", force: :cascade do |t|`

but the bigserial is till there:

```ruby
  create_table "foo_users", primary_key: "rowid_1", force: :cascade do |t|
    t.bigint "foo_id"
    t.bigint "user_id"
    t.bigserial "rowid", null: false
  end
```

**Comment by sandstrom** [comment]
Would also be good if you kept this (or a related) issue open, pointing back to (referencing) the issue in cockroachdb itself, that tracks support for unique id being a tuple (union of N columns).

**Comment by keithdoggett** [comment]
@rafiss do you know if support for this is going to be added in the future? I can make the change to ignore `id: false` for now if you think that makes sense, but you might have a better idea of how we should handle this.

**Comment by rafiss** [comment]
>> Would also be good if you kept this (or a related) issue open, pointing back to (referencing) the issue in cockroachdb itself, that tracks support for unique id being a tuple (union of N columns).
> 
> do you know if support for this is going to be added in the future?

Support for what exactly? CRDB does already support composite primary keys. For example, see the first example at: https://www.cockroachlabs.com/docs/stable/primary-key.html#example

I was having trouble following this issue. The `rowid` column should only be created when no primary key is specified; if there already is a column named `rowid`, then CRDB will try to make `rowid_n`. The issue with a `rowid_n` column being made when it shouldn't might be related to how `rowid` is a "hidden" column -- if you `select *` from the table, it will not include the hidden `rowid` column. So rather than not displaying the column at all, maybe using this `hidden` attribute will prevent ActiveRecord from making the duplicate column. You can query `information_schema.columns` to see that a column is hidden, but let me know if you'd need another way of inspecting this info. This also is evidence that maybe ActiveRecord isn't correctly introspecting the primary key constraint.

Concretely, one thing that would help is if I could see the SQL that is generated when ActiveRecord unloads/reloads the schema.

**Comment by sandstrom** [comment]
Don't know if this helps, but a join table in ActiveRecord would look like this:

```ruby
class CreateAssembliesPartsJoinTable < ActiveRecord::Migration[6.0]
  def change
    create_table :assemblies_parts, id: false do |t|
      t.bigint :assembly_id
      t.bigint :part_id
    end

    add_index :assemblies_parts, :assembly_id
    add_index :assemblies_parts, :part_id
  end
end
```

source: https://guides.rubyonrails.org/association_basics.html

I don't know how the PostgresqlAdapter in ActiveRecord would understand that this is composite primary key (does Postgres care about that?). If there is an existing mechanism in ActiveRecord, you could probably hook into it.

Otherwise, the solution could be to manually configure the primary key. There seems to be different ways of doing that, but a few examples here: https://stackoverflow.com/questions/4769725/rails-migration-create-table-primary-key

One of them is:

```ruby
create_table :global_feeds, {:id => false} do |t|
  t.string :guid
  t.text :title
  t.text :subtitle
  t.timestamps
end
execute "ALTER TABLE global_feeds ADD PRIMARY KEY (guid);"
```

Bunch of relevant stuff in https://guides.rubyonrails.org/active_record_migrations.html too I'd guess

*Mix of random thoughts, hope it's helpful*

**Comment by keithdoggett** [comment]
> support for what exactly?

Sorry if this unclear, and @Piioo can help clarify, but I believe the intention here is to make a join table without a primary key, so will there be support for tables without primary keys in the future? This is possible to do in Postgres and, I'd need to double-check this, but if the original migration was done with the PosgresAdapter it would create a table without a primary key (because of the `id: false` option).

Per the CockroachDB docs (https://www.cockroachlabs.com/docs/stable/create-table.html#create-a-table), it's not possible to create a table without a primary key and if one is created without specifying a primary key, `rowid` is created. My suggestion was just to not allow `id: false` or if that is passed, make it detect that `rowid` is the actual primary key.

> So rather than not displaying the column at all, maybe using this hidden attribute will prevent ActiveRecord from making the duplicate column.

Thanks that's helpful, I think we probably do need to modify how we detect primary keys since some of them could be `hidden`.

> Concretely, one thing that would help is if I could see the SQL that is generated when ActiveRecord unloads/reloads the schema.

I will try to get that together soon.

**Comment by Piioo** [comment]
For me it does not matter if we do not allow `id: false` or something else. I need a working schema.rb

The rowid may be there in the join table, it does not matter, but the schema.rb should handle this somehow.

**Comment by sandstrom** [comment]
I'd say that for join tables you'll always want a primary key, but it's a composite. The example rafiss quoted is a join table:

```SQL
CREATE TABLE IF NOT EXISTS inventories (
    product_id        INT,
    warehouse_id      INT,
    quantity_on_hand  INT NOT NULL,
    PRIMARY KEY (product_id, warehouse_id)
  );
```

So what you need is to figure out how you can make sure that an active record migration running under your adapter would result in the SQL quoted above.

I think the canonical way of telling `create_table` it should create a table with a composite key, is something like this:

```ruby
create_table(:orders, primary_key: [:product_id, :client_id]) do |t|
  t.belongs_to :product
  t.belongs_to :client
end
```

Which would result in this SQL snippet:
```sql
CREATE TABLE order (
    product_id bigint NOT NULL,
    client_id bigint NOT NULL
);

ALTER TABLE ONLY "orders"
  ADD CONSTRAINT orders_pkey PRIMARY KEY (product_id, client_id);
```

So your challenge is probably to modify your adapter to somehow instead return the top-most quoted SQL structure.

**Comment by keithdoggett** [comment]
Here's a test in ActiveRecord 6.1 and CockroachDB 21.1.

Migration:

```rb
class CreateFooBars < ActiveRecord::Migration[6.1]
  def change
    create_table :foo_bars, id: false do |t|
      t.uuid :foo_id
      t.uuid :bar_id

      t.timestamps
    end
  end
end
```

First I run `rake db:drop db:create`

Then `rake db:migrate`

SQL Generated:
```sql
CREATE TABLE "foo_bars" ("foo_id" uuid, "bar_id" uuid, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)
```

Schema.rb:
```rb
  create_table "foo_bars", id: false, force: :cascade do |t|
    t.uuid "foo_id"
    t.uuid "bar_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.bigserial "rowid", null: false
  end
```
\d foo_bars:
```
  column_name | data_type | is_nullable | column_default | generation_expression |  indices  | is_hidden
--------------+-----------+-------------+----------------+-----------------------+-----------+------------
  foo_id      | UUID      |    true     | NULL           |                       | {}        |   false
  bar_id      | UUID      |    true     | NULL           |                       | {}        |   false
  created_at  | TIMESTAMP |    false    | NULL           |                       | {}        |   false
  updated_at  | TIMESTAMP |    false    | NULL           |                       | {}        |   false
  rowid       | INT8      |    false    | unique_rowid() |                       | {primary} |   true
```

Now, I run `rake db:drop db:create db:schema:load`

SQL Generated:
```sql
CREATE TABLE "foo_bars" ("foo_id" uuid, "bar_id" uuid, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, "rowid" bigserial NOT NULL)
```

Schema.rb:
```rb
  create_table "foo_bars", id: false, force: :cascade do |t|
    t.uuid "foo_id"
    t.uuid "bar_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.bigserial "rowid", null: false
  end
```

\d foo_bars:
```
  column_name | data_type | is_nullable | column_default | generation_expression |  indices  | is_hidden
--------------+-----------+-------------+----------------+-----------------------+-----------+------------
  foo_id      | UUID      |    true     | NULL           |                       | {}        |   false
  bar_id      | UUID      |    true     | NULL           |                       | {}        |   false
  created_at  | TIMESTAMP |    false    | NULL           |                       | {}        |   false
  updated_at  | TIMESTAMP |    false    | NULL           |                       | {}        |   false
  rowid       | INT8      |    false    | unique_rowid() |                       | {}        |   false
  rowid_1     | INT8      |    false    | unique_rowid() |                       | {primary} |   true
```

The  issue is clearer now. When the migration is ran, `rowid` is added to the schema through this method:

https://github.com/cockroachdb/activerecord-cockroachdb-adapter/blob/876afa262f023008a16ab8db36c54a85955445fd/lib/active_record/connection_adapters/cockroachdb/schema_statements.rb#L17-L33

Then when the database is loaded through the schema, the SQL generated to create the table adds a `rowid` column, but not as a primary key, just as another column which means `rowid_1` is created as the primary key.

The comment in `primary_key` says that the intention is not to treat `rowid` as a primary key, but that may be the incorrect way to handle this and it should probably set `rowid` as the primary key in this case.

**Comment by sandstrom** [comment]
@keithdoggett did you have a change to look at my suggestion above? (https://github.com/cockroachdb/activerecord-cockroachdb-adapter/issues/203#issuecomment-863383879)

I think that comment explains what's needed to fix this issue, and it doesn't look too complicated.

**Comment by sandstrom** [comment]
Friendly ping @rafiss 😄

**Comment by sandstrom** [comment]
@keithdoggett did you have a change to look at my suggestion above? (https://github.com/cockroachdb/activerecord-cockroachdb-adapter/issues/203#issuecomment-863383879)

I think that comment explains what's needed to fix this issue, and it doesn't look too complicated. Would be awesome if CockroachDB supported this, since join tables are very common.

**Comment by sandstrom** [comment]
friendly ping @rafiss 😄 

*This issue and a few of the other issues in this repo is what's currently blocking us from trying to move our Rails app over to CockroachDB. It's great that you've added this adapter, it's just that it needs a bit more polish and love ❤️.*

*It doesn't really seem like anyone is actively working more than a handful of hours a month on this right now. With some concerted effort over a few weeks you could take this to a level where it's a reasonable candidate against PostgreSQL.*

**Comment by rafiss** [comment]
Thanks for the ping. I understand the problem and agree there's a bug here.

As a workaround in the meantime, could you add a primary key to your table? For example, for table `foo_bars`, it seems useful and important to make the primary key `(foo, bar)`. Otherwise your join table could have duplicate rows for the same values. Adding that primary key should also improve join performance.

**Comment by sandstrom** [comment]
@rafiss Thanks for taking time answering. 🙏🏻 

I know there are workarounds. But right now we're hesitant to move over to CockroachDB when there are a few too many issues like this + the cadence on the repo is a little low. For example, if we'd start a migration for our codebase we'd certainly run into a bunch of issues, some of them we could probably solve with workarounds, but others may require updates to this adapter. But right now it doesn't feel like this adapter is advancing much from month to month.

Anyway, we're still interested in CockroachDB (I think it's an interesting database!) and I'll continue to keep an eye on this repo for progress.
