### ISSUE TITLE
ActiveRecord 5.1.5 rake db:test:prepare fails with search for `postgres`

### ISSUE THREAD

**Issue by bherrup** [cockroachdb/activerecord-cockroachdb-adapter#26]
```
ActiveRecord::StatementInvalid: PG::InvalidCatalogName: ERROR:  database "postgres" does not exist
:             SELECT t.oid, t.typname
            FROM pg_type as t
            WHERE t.typname IN ('int2', 'int4', 'int8', 'oid', 'float4', 'float8', 'bool')
```

**Comment by Cikey** [comment]
As a workaround, you can create an empty database `postgres`. This allows the catalogue lockup to continue. If you have a secure cluster, make sure that your rails user can access the postgres db. 

A permanent solution will probably be https://github.com/cockroachdb/cockroach/pull/24735

**Comment by phosphor1879** [comment]
I was stuck on this for awhile, not knowing how to even do the workaround, which was made a bit more complicated due to using docker, and not being able to get a cockroachdb binary to run in my alpine rails container. Eventually I went with a workaround in which I added the docker client binary to the image, mounted the `docker.sock` as a volume, and put this early in my application startup, before any rake db:* commands are executed:

`system("docker exec -it #{cockroach_container_name} ./cockroach sql  --insecure -e 'CREATE DATABASE postgres'")`

**Comment by knz** [comment]
So you know, the next CockroachDB release will pre-create the `postgres` database.
