### ISSUE TITLE
 Rails migration fails after upgrading from 24.1 to 24.2 - no indexes found & no support for composite primary keys

### ISSUE THREAD

**Issue by mowinslow2** [cockroachdb/activerecord-cockroachdb-adapter#344]
After upgrading from 24.1 to 24.2, there is a `no indexes found` error and a `no support for composite primary keys` when running rails migration. This seems to be happening exclusively on Regional by Row tables with PKs and indexes that include the hidden `crdb_region` column 

It looks like the culprit could be that the `crdb_region` column is now included in `pg_index.indkey`

**Issue 1**
```
== migrating ============================
-- remove_index(:redacted_table_name, "redacted_table_name_id", {:algorithm=>:concurrently})
rails aborted!
StandardError: An error has occurred, all later migrations canceled: (StandardError)

No indexes found on redacted_table_name with the options provided.

Caused by:
ArgumentError: No indexes found on redacted_table_name with the options provided. (ArgumentError)
            raise ArgumentError, "No indexes found on #{table_name} with the options provided."
Tasks: TOP => db:migrate
```

**Issue 2**
```
WARNING: Active Record does not support composite primary key.
redacted_table_name has composite primary key. Composite primary key is ignored.
```

**Comment by rafiss** [comment]
I am curious if table definitions like this also cause the issue:
```
CREATE TABLE t(a INT NOT VISIBLE, b INT, PRIMARY KEY (a,b));

CREATE TABLE t(a INT PRIMARY KEY USING HASH WITH (bucket_count=4));
```

**Comment by BuonOmo** [comment]
I've started looking for a reproduction on #345. The two create tables you showed @rafiss are simply not showing any index, and this didn't change since 23.2. Maybe because of the `d.indisprimary = 'f'` in the [#indexes method](https://github.com/rails/rails/blob/87e7ad666575fa903781ac5baed6ca9ad5b807b0/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L86-L91). This looks like a behaviour we might not want, but it has nothing to do with the migration from 24.1 to 24.2.

I do not yet have access to a regional table plan to see if I can reproduce the reported issue. But I will soon hopefully!
